### ISSUE TITLE
Add Mac OS

### ISSUE THREAD

**Issue by Korijn** [conda-forge/wxpython-feedstock#2]

**Comment by Korijn** [comment]
See #3. The built package works. Test fails however due to some unknown roblem with `conda inspect linkages`.

**Comment by Korijn** [comment]
Seems to sorted now. Still timeouts though.

@berendkleinhaneveld and I will follow up with manual uploads later.

**Comment by cpbotha** [comment]
After quite some effort, I managed to make this conda-recipe which gets the latest wxPython (as of 20171113) built on macOS, see https://github.com/cpbotha/wxpython-feedstock/commits/master

First built packages on here: https://anaconda.org/cpbotha/wxpython

Trying to run a small sample with python however, gives the unsurprising:
```
$ python ./lib/plot/examples/demo.py
This program needs access to the screen. Please run with a
Framework build of python, and only when you are logged in
on the main display of your Mac.
```

Oh yes, we need to use python.app for this. However, this time we are surprised by:
```
>>> import wx
Fatal Python error: PyThreadState_Get: no current thread

/Users/cpbotha/miniconda3/envs/skcg/bin/python.app: line 3: 57051 Abort trap: 6           /Users/cpbotha/miniconda3/envs/skcg/python.app/Contents/MacOS/python "$@"
```

I am hoping that @ChrisBarker-NOAA (hi there Chris, I remember you from way back on the VTK mailing lists!) might be able to shed some light, as 1. I forked his wxpython-feedstock as basis and 2. his name comes up a lot in discussions around anaconda and python.app.

I have `otool`d and `dtruss`d, but can't find where my wxpython package is being contaminated by the wrong Python libraries, which often seems to be the source of the "no current thread" error. Currently I'm wondering whether I should have done the whole build with `python.app`.

Any suggestions would be greatly appreciated!

**Comment by ChrisBarker-NOAA** [comment]
I’ll try to take a look when I get a chance, but that may not be for a week
or so.

Meanwhile, it does not look familiar—so no clue :-(

-CHB

Sent from my iPhone

On Oct 17, 2017, at 8:18 AM, Charl P. Botha <notifications@github.com>
wrote:

After quite some effort, I managed to make this conda-recipe which gets the
latest wxPython (as of 20171113) built on macOS, see
https://github.com/cpbotha/wxpython-feedstock/commits/master

First built packages on here: https://anaconda.org/cpbotha/wxpython

Trying to run a small sample with python however, gives the unsurprising:

$ python ./lib/plot/examples/demo.py
This program needs access to the screen. Please run with a
Framework build of python, and only when you are logged in
on the main display of your Mac.

Oh yes, we need to use python.app for this. However, this time we are
surprised by:

>>> import wx
Fatal Python error: PyThreadState_Get: no current thread

/Users/cpbotha/miniconda3/envs/skcg/bin/python.app: line 3: 57051
Abort trap: 6
/Users/cpbotha/miniconda3/envs/skcg/python.app/Contents/MacOS/python
"$@"

I am hoping that @ChrisBarker-NOAA <https://github.com/chrisbarker-noaa>
(hi there Chris, I remember you from way back on the VTK mailing lists!)
might be able to shed some light, as 1. I forked his wxpython-feedstock as
basis and 2. his name comes up a lot in discussions around anaconda and
python.app.

I have otoold and dtrussd, but can't find where my wxpython package is
being contaminated by the wrong Python libraries, which often seems to be
the source of the "no current thread" error. Currently I'm wondering
whether I should have done the whole build with python.app.

Any suggestions would be greatly appreciated!

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/conda-forge/wxpython-feedstock/issues/2#issuecomment-337263563>,
or mute the thread

**Comment by cpbotha** [comment]
Hi all, I got this working.

The problem is that python.app simply bundles whatever Python binary is available from its conda build dependencies. All of my other packages come from conda-forge whereas python.app is only available from anaconda. This was causing the "no current thread error"

Anyways, if you install wxpython phoenix (latest greatest HEAD) and python.app from my https://anaconda.org/cpbotha you have a fully working wxpython setup on macos with Python 3.6.

**Comment by ChrisBarker-NOAA** [comment]
Hmm,

Do we need a python.app in conda-forge?

Though it’s really not the right way to foot anyway :-(

-CHB

Sent from my iPhone

On Oct 17, 2017, at 11:49 PM, Charl P. Botha <notifications@github.com>
wrote:

Hi all, I got this working.

The problem is that python.app simply bundles whatever Python binary is
available from its conda build dependencies. All of my other packages come
from conda-forge whereas python.app is only available from anaconda. This
was causing the "no current thread error"

Anyways, if you install wxpython phoenix (latest greatest HEAD) and
python.app from my https://anaconda.org/cpbotha you have a fully working
wxpython setup on macos with Python 3.6.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/conda-forge/wxpython-feedstock/issues/2#issuecomment-337476673>,
or mute the thread

**Comment by cpbotha** [comment]
Although I agree with you it's not the right approach to start with, it is the one chosen by Continuum.

Yes, safest would be to have python.app in conda-forge which matches the packaged python versions.

**Comment by Korijn** [comment]
As you can see, I've set up a PR for python.app to conda-forge/staged-recipes and I've also opened a PR to this feedstock for @cpbotha's changes to the recipe to add OS X support.

**Comment by cpbotha** [comment]
Awesome thank you very much @Korijn !

I am currently very quickly testing the `osx_is_app` build key, see https://conda.io/docs/user-guide/tasks/build-packages/define-metadata.html#python-app (this is so that wxpython entry points get `python.app` as their shebang, which they need to run)

If this works as expected I'm pushing two more commits to my fork (that one, and the minor selector whitespace issue that was flagged by the linter). Will it later be possible to pull in these changes to your official package?

**Comment by Korijn** [comment]
You can submit a PR to my PR which is [a fork of your fork](https://github.com/Korijn/wxpython-feedstock/) while it's open to get your changes in there.

If it's merged, you can just open another PR to the feedstock, of course.

**Comment by cpbotha** [comment]
github inception!

**Comment by cpbotha** [comment]
Here you go! https://github.com/Korijn/wxpython-feedstock/pull/1

(I just tested on macOS, entrypoints are now 73% improved.)

**Comment by Korijn** [comment]
It seems we got it done in #9 but the build will sadly not complete within timeout limits. We'll have to reset to manual builds and uploading them to conda-forge.

It seems #6 is our only remaining option if we want to automate the builds here on conda-forge.

**Comment by ChrisBarker-NOAA** [comment]
yeah -- while I"d rather have it all build "properly" -- I think there is a lot to be said for something that actually works.

We've been trying to get more CI time since conda-forge began, at some point we need to cut bait.

"practicality beats purity" and all that.

**Comment by Korijn** [comment]
I can't peek into Anaconda's bank account, but it is hard to see how $129 /mo is really too much for such a big group?

**Comment by ChrisBarker-NOAA** [comment]
On Wed, Oct 25, 2017 at 1:37 PM, Korijn van Golen <notifications@github.com>
wrote:

> I can't peek into Anaconda's bank account, but it is hard to see how $129
> /mo is really too much for such a big group?
>
Anaconda doesn't fund conda-forge -- we are all volunteer.

There is an effort to become a num_focus sponsored project so that folks
could donate, but I don't know if we'd get enough donations to keep a paid
CI service going....

The other option if for Anaconda to pick this one up for defaults. They do
have an older version of wxPython in there, but haven't updated it.

However, wxPython 4.* is new, and "pre-release" and changing fast, so I
don't know that they'd want to take it on anyway.

-CHB



-- 

Christopher Barker, Ph.D.
Oceanographer

Emergency Response Division
NOAA/NOS/OR&R            (206) 526-6959   voice
7600 Sand Point Way NE   (206) 526-6329   fax
Seattle, WA  98115       (206) 526-6317   main reception

Chris.Barker@noaa.gov

**Comment by cpbotha** [comment]
@Korijn when you removed the xquartz dependency, the osx build managed to complete within the time limit. Was that a once-off occurrence?

**Comment by Korijn** [comment]
I hadn't noticed, can you point me to the build log?

Regardless I will open another PR to find out. :)

**Comment by cpbotha** [comment]
I was continuously reloading the osx builds. Unless I was dreaming, they all completed under 47 minutes.

**Comment by cpbotha** [comment]
@Korijn I think I was watching the circleci and not the travis, I am very sorry.

**Comment by Korijn** [comment]
:disappointed:

**Comment by cpbotha** [comment]
@Korijn and @ChrisBarker-NOAA based on this thread: https://github.com/travis-ci/travis-ci/issues/2736#issuecomment-111716948 -- we could mail Travis support and request some extra build time for conda-forge.

Has anyone tried this?

**Comment by Korijn** [comment]
Two years ago I tried for VTK, but got no reply. Feel free to give it another shot?
