### ISSUE TITLE
Installing wxWidgets headers and *.lib

### ISSUE THREAD

**Issue by nsimakov** [conda-forge/wxpython-feedstock#28]
Issue: Feature Request/Discussion

Our C++/Python code uses mostly wxWidgets with few windows/panels done with wxPython, we are moving towards using wxPython more. In addition we want to used conda to manage our library dependencies, most of our other dependencies are already in conda forge. 

In order for this pie to work it is impotent to use same wxWidgets libraries in C++ part as one used in wxPython on python side. So the question is: is there interest to add wxWidgets headers and *.lib to wxpython package?

And another question is how to implement it best. I have started playing with it and debating should I update build.py or create bld.bat? There is also possibility to use post-linking script, but according to docs this script is not desired and should only operate on installed files.

Thanks,
Nikolay

**Comment by ocefpaf** [comment]
I'm not exactly sure what that entails but I'm OK trying it. Maybe the `.lib` and headers can be sub-package?

**Comment by nsimakov** [comment]
I add headers and library copying:
https://github.com/nsimakov/wxpython-feedstock/blob/copying_headers_and_libs/recipe/bld.bat
https://anaconda.org/nsimakov/wxpython

The size grow just a little bit but there are a lot of headers, I will take a look into submodules

**Comment by nsimakov** [comment]
Well, wxwidgets .h's and .lib's as add-on subpackage have sense. Here is my branch on that:

https://github.com/nsimakov/wxpython-feedstock/tree/copying_headers_and_libs

and anaconda cloud:
https://anaconda.org/nsimakov/wxpython
https://anaconda.org/nsimakov/wxpython-wxwidgets

Pull request it for further discussion?

**Comment by ocefpaf** [comment]
> Pull request it for further discussion?

Please do :grimacing:

**Comment by timsnyder** [comment]
This issue is interesting to me because I have a wxpython app that we've supported only on Linux platforms and want to add support for macOS.  The Linux wxpython packages from conda-forge (and defaults before cf) include the wxWidgets headers in `include/` and shared libraries in `lib/`.

Looking at both osx-64 and win-64 packages, it appears that the wxWidgets headers are not included at all and the shared libraries are not in `lib/`, they are buried down in `$SP_DIR/wx` (i.e. `Lib/site-packages/wx` for `win-64` or `lib/pythonX.Y/site-packages/wx` on `osx-64`).  I say _buried_ because it is unlikely that any C/C++ code trying to compile against wxWidgets is going to link against libs that are inside the python site-packages directory (unless that code happens to be a C python extension?).

Building wxpython using pip seems to inherently vendor wxWidgets, including it in the build and packaging of wxpython.  A longer-term and more universally applicable solution might be to break wxWidgets build out of wxpython and reference it as a dependency of wxpython.  That would enable C/C++ usage of wxWidgets without wxpython and a platform consistent build that includes the headers for all platforms and also places the wxWidgets lib artifacts in the `lib/` directory where they belong.

I would be willing to create the separate wxWidgets feedstock, become a maintainer of it and also submit a PR here that would use it.  I'm not in a hurry to do this and I'd be curious what @ocefpaf and @constantinpape think of this idea before spending much time on it.

@nsimakov , are you happily using your own wxpython and wxpython-wxwidgets packages?  Are you still wanting to get your changes upstreamed into conda-forge?  Do you have need for osx or linux packages that contain the same artifacts or are you only concerned with Windows platform?

**Comment by ocefpaf** [comment]
> I would be willing to create the separate wxWidgets feedstock, become a maintainer of it and also submit a PR here that would use it. I'm not in a hurry to do this and I'd be curious what @ocefpaf and @constantinpape think of this idea before spending much time on it.

I'm no longer deeply involved in projects that use `wxpython` so my opinion here is not based on experience and/or what I think it is better for the users.

With that said. Maybe a new feedstock would be better and easier to maintain. Also, people who don't need that part would have a smaller `wxpython`, right?

However, if this is crucial for users, I'l also OK copying those header and libs here.

**Comment by timsnyder** [comment]
I opened a topic in the wxPython Discourse asking that community if they have any suggestions: https://discuss.wxpython.org/t/including-wxwidgets-headers-in-windows-and-macos-builds/34471

When I started looking splitting the two builds apart, I was reminded of [wxPython's advice on Building WxWidget's separately](https://github.com/wxWidgets/Phoenix/#building-wxwidgets):
![image](https://user-images.githubusercontent.com/83846/76646123-6c66e000-6528-11ea-83e7-e2befcee1fb4.png)

**Comment by timsnyder** [comment]
Given that I'm not concerned about having the absolute latest wxWidgets version, I want one that is known to work with wxPython, I think that keeping only the wxpython-feedstock and perhaps having split package outputs is the way to go.

**Comment by nsimakov** [comment]
It used to work. But it was long time ago and I am not sure what we are using for the dependencies at this point for that project. Eventually we want to move to conda-forge for both development and deployment.

**Comment by timsnyder** [comment]
Thanks for the update @nsimakov .  Hopefully I'll have time to take another pass at getting this done.
